### ISSUE TITLE
off topic: synthetic bt2020 to dci-p3 profile

### ISSUE THREAD

**Issue by 24fpsDaVinci** [quietvoid/pgen_client#1]
i came across this [post](https://www.avsforum.com/threads/2018-lg-oled-calibration-and-user-settings-no-price-talk.2962814/page-191#post-61381379) where you mention a synthetic "bt2020 to dci-p3" profile. is this a bt.2020 profile that tagets dci-p3 primaries? just wondering how I can generate such a profile for testing.

**Comment by quietvoid** [comment]
You can create it with DisplayCAL.

**Comment by 24fpsDaVinci** [comment]
ive been using displaycal synthetic profile creator, i'm just not sure what "bt2020 to dci-p3" means exactly? i've been struggling with hdr calibration for awhile. the bt2020 profiles generated by displaycal all have really strong gamut compression, red becomes pink after applying the 3d lut. i've tried pseudo calman way of measuring WRGB and creating synthetic profile then using collink but results not good either.

do you mean the panel native gamut is P3 and youre doing bt2020 to P3 in collink?

**Comment by quietvoid** [comment]
I don't remember how it was done and I can't check at the moment.  
It was all within DisplayCAL though.

**Comment by 24fpsDaVinci** [comment]
for future references, we gotta use xy coordinates only for synthetic HDR profiles, XYZ will cause luminance errors and dci-p3 to shrink.

**Comment by 24fpsDaVinci** [comment]
I tested using smpte431_P3 as the source profile on the 3Dlut page it seems to work ok without blowing out highlights unlike when choosing rec2020 as source profile. 

I'm guessing internally in the TV pipeline theres a matrix somewhere converting BT2020 to P3? and LG treats HDR content as p3 not bt2020.. 

I recall in early calman tutorials they chose P3D65 as the target profile when calibrating HDR.
