### ISSUE TITLE
show patterns included with PGen?

### ISSUE THREAD

**Issue by nefilim** [quietvoid/pgen_client#20]
Is it possible to show patterns included with PGenerator, eg https://www.displaycalibrations.com/pgenerator_order.html ?

ps is the PGen API documented somewhere? or even better, is the source available somewhere?

**Comment by quietvoid** [comment]
> Is it possible to show patterns included with PGenerator, eg

It is but I don't have any patterns on mine so I haven't tried.

> ps is the PGen API documented somewhere? or even better, is the source available somewhere?

The source is available on the device itself for the daemon.
There are just a few executables that are used for the actual pattern displaying part, for which the source and build instructions are not really available.

If you know what you are doing, you can either read the DeviceControl code or capture packets for communication from ColourSpace.

**Comment by nefilim** [comment]
thanks for the pointers. more perl 🤦
